version: "3.8"
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_TITLE=Moda Selfie Ayna
      - REACT_APP_VERSION=1.0.0
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: unless-stopped 